services:
  minio:
    image: minio/minio
    container_name: minio
    env_file:
      - ./env/minio.env
    volumes:
      - ./storage:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - network

  hive-metastore:
    container_name: hive-metastore
    build: ./hive
    restart: unless-stopped
    ports:
      - "9083:9083"
    networks:
      - network

  presto:
    container_name: presto
    build: ./presto/config
    restart: unless-stopped
    ports:
      - "8100:8080"
    networks:
      - network
 
  metabase:
    container_name: metabase
    image: metabase/metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase.db
    networks:
      - network

  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   hostname: postgres
  #   environment:
  #     POSTGRES_USER: metabase
  #     POSTGRES_PASSWORD: metabase
  #     POSTGRES_DB: metabaseappdb
  #   volumes:
  #     - data_postgres:/var/lib/postgresql/data
  #   networks:
  #     - network

  # spark:
  #   container_name: spark-master
  #   build: ./spark
  #   ports:
  #     - "7077:7077"
  #     - "8080:8080"
  #     - "8081:8081"
  #   networks:
  #     - network

  # spark-worker:
  #   container_name: spark-worker
  #   env_file:
  #     - ./env/spark.env
  #   build: .
  #   volumes:
  #     - ./spark:/spark
  #   networks:
  #     - network

volumes:
  storage:
  data_postgres:

networks:
  network:
    driver: bridge
